export { default as Intro } from './Intro';
export { default as About } from './About';
export { default as Features } from './Features';
export { default as Resources } from './Resources';
export { default as Partnerships } from './Partnerships';
export { default as Contact } from './Contact';
export { default as Button } from './Button';
export { default as ListIdeas } from './ListIdeas';
export { default as RegisterIdea } from './RegisterIdea';
