export default {
	searchState: {
		page: 1,
		query: '',
		refinementList: {
			category: [],
		},
	},
	resultsState: {
		rawResults: [
			{
				exhaustiveFacetsCount: true,
				exhaustiveNbHits: true,
				facets: {},
				hits: [
					{
						application_examples: null,
						application_mode:
							'Li ca ceapeabo tovimi igtilezo udpuz uga su uzo cuhi sece pikan.',
						category: 'Oferta de Água/Armazenamento',
						contribution: 'Ru egefuhge.',
						created_at: '2020-09-22 21:06:28',
						description:
							'Kodopifi sammehor voecara wu dietu je zedsande lo nemnoriv zi metoeju na bajo.',
						entailes_problem:
							'Bimpa havla ibru tus sogjo dezecaw jozto kosedzo rakhojup gatsud obe.',
						id: 52,
						installation_time: 34,
						likes: 0,
						objectID: 'technology-52',
						patent: 1,
						patent_number: null,
						primary_purpose: 'Fobsomir ikepet icpu cickavcib wedug.',
						private: 0,
						requirements: 'Kemferuh maddovo om .',
						risks: 'Goel sozuhpid mol ep.',
						secondary_purpose: 'Of date vemcodnig gubkeji uzato.',
						slug: 'gesbib-powev-sodzomjikm-10',
						solves_problem: 'Bigzacu cien wekgeg jivmu dorcuze iwuuzoza .',
						status: 'DRAFT',
						thumbnail_id: null,
						title: 'Gesbib powev sodzomjikm.',
						updated_at: '2020-09-22 21:06:35',
						users: [
							{
								address: null,
								address2: null,
								birth_date: null,
								city: null,
								company: null,
								country: null,
								cpf: null,
								created_at: '2020-09-02 13:59:58',
								district: null,
								email: 'sabiatestinge2e@gmail.com',
								first_name: 'FirstName',
								full_name: 'FirstName LastName',
								id: 11,
								last_name: 'LastName',
								lattes_id: null,
								phone_number: null,
								pivot: { user_id: 11, technology_id: 52, role: 'OWNER' },
								role_id: 1,
								state: null,
								status: 'verified',
								updated_at: '2020-09-02 13:59:58',
								zipcode: null,
							},
						],
					},
					{
						application_examples: null,
						application_mode:
							'Li ca ceapeabo tovimi igtilezo udpuz uga su uzo cuhi sece pikan.',
						category: 'Oferta de Água/Armazenamento',
						contribution: 'Ru egefuhge.',
						created_at: '2020-09-21 22:03:33',
						description:
							'Kodopifi sammehor voecara wu dietu je zedsande lo nemnoriv zi metoeju na bajo.',
						entailes_problem:
							'Bimpa havla ibru tus sogjo dezecaw jozto kosedzo rakhojup gatsud obe.',
						id: 51,
						installation_time: 34,
						likes: 0,
						objectID: 'technology-51',
						patent: 1,
						patent_number: null,
						primary_purpose: 'Fobsomir ikepet icpu cickavcib wedug.',
						private: 0,
						requirements: 'Kemferuh maddovo om .',
						risks: 'Goel sozuhpid mol ep.',
						secondary_purpose: 'Of date vemcodnig gubkeji uzato.',
						slug: 'gesbib-powev-sodzomjikm-9',
						solves_problem: 'Bigzacu cien wekgeg jivmu dorcuze iwuuzoza .',
						status: 'DRAFT',
						thumbnail_id: null,
						title: 'Gesbib powev sodzomjikm.',
						updated_at: '2020-09-21 22:03:40',
						users: [
							{
								address: null,
								address2: null,
								birth_date: null,
								city: null,
								company: null,
								country: null,
								cpf: null,
								created_at: '2020-09-02 13:59:58',
								district: null,
								email: 'sabiatestinge2e@gmail.com',
								first_name: 'FirstName',
								full_name: 'FirstName LastName',
								id: 11,
								last_name: 'LastName',
								lattes_id: null,
								phone_number: null,
								pivot: { user_id: 11, technology_id: 51, role: 'OWNER' },
								role_id: 1,
								state: null,
								status: 'verified',
								updated_at: '2020-09-02 13:59:58',
								zipcode: null,
							},
						],
					},
				],
				hitsPerPage: 12,
				index: 'searchable_data',
				nbHits: 22,
				nbPages: 2,
				page: 0,
				params:
					'highlightPreTag=%3Cais-highlight-0000000000%3E&highlightPostTag=%3C%2Fais-highlight-0000000000%3E&query=&maxValuesPerFacet=20&hitsPerPage=12&page=0&facets=%5B%22private%22%2C%22category%22%5D&tagFilters=',
				processingTimeMS: 1,
				query: '',
			},
		],
		state: {
			disjunctiveFacets: ['private', 'category'],
			disjunctiveFacetsRefinements: {},
			facets: [],
			facetsExcludes: {},
			facetsRefinements: {},
			hierarchicalFacets: [],
			hierarchicalFacetsRefinements: {},
			highlightPostTag: '</ais-highlight-0000000000>',
			highlightPreTag: '<ais-highlight-0000000000>',
			hitsPerPage: 12,
			index: 'searchable_data',
			maxValuesPerFacet: 20,
			numericRefinements: {},
			page: 0,
			query: '',
			tagRefinements: [],
		},
	},
};
