const ERRORS_CODE = {
	INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
	UNAUTHORIZED_ACCESS: 'UNAUTHORIZED_ACCESS',
	VALIDATION_ERROR: 'VALIDATION_ERROR',
	INVALID_EMAIL: 'INVALID_EMAIL',
	UNVERIFIED_EMAIL: 'UNVERIFIED_EMAIL',
	ALREADY_VERIFIED_EMAIL: 'ALREADY_VERIFIED_EMAIL',
	INVALID_TOKEN: 'INVALID_TOKEN',
	EXPIRED_TOKEN: 'EXPIRED_TOKEN',
	MISSING_DEFAULT_ROLE: 'MISSING_DEFAULT_ROLE',
	RESOURCE_NOT_FOUND: 'RESOURCE_NOT_FOUND',
	RESOURCE_DELETED_ERROR: 'RESOURCE_DELETED_ERROR',
	RESOURCE_SAVING_ERROR: 'RESOURCE_SAVING_ERROR',
	PASSWORD_NOT_MATCH: 'PASSWORD_NOT_MATCH',
	UNIQUE_TECHNOLOGY_COST_ERROR: 'UNIQUE_TECHNOLOGY_COST_ERROR',
	TERMSOFUSE: 'TERMSOFUSE',
	STATUS_NO_ALLOWED_FOR_REVIEW: 'STATUS_NO_ALLOWED_FOR_REVIEW',
	REGISTRATION_UNCOMPLETED: 'REGISTRATION_UNCOMPLETED',
	STATUS_NO_ALLOWED_FOR_OPERATION: 'STATUS_NO_ALLOWED_FOR_OPERATION',
	BAD_FORMATTED_ID: 'BAD_FORMATTED_ID',
	USER_WITHOUT_INSTITUTION: 'USER_WITHOUT_INSTITUTION',
	UNIQUE_TERM_ERROR: 'UNIQUE_TERM_ERROR',
};

module.exports.errorPayload = (code, message) => {
	return {
		error: {
			error_code: code,
			message,
		},
	};
};

module.exports.errors = ERRORS_CODE;
