import React from 'react';
import { render } from 'test-utils';
import Page from '../[technology]/index';

const technology = {
	id: Math.ceil(Math.random() * 100),
	title: 'Agebavzi niko zaro.',
	slug: 'agebavzi-niko-zaro',
	description: 'Gec hik gir.',
	private: 1,
	thumbnail_id: null,
	likes: 1,
	patent: 0,
	patent_number: 'deXnvEMZ',
	primary_purpose: 'Rirut lavdes safbuz.',
	secondary_purpose: ['Fet', 'ejhagi', 'pa'],
	application_mode: 'Ci apa wovjejoru.',
	application_examples: 'Pumasaz sojkowi bikitmus.',
	installation_time: 465,
	solves_problem: 'Umfecet kig nepda.',
	entailes_problem: 'Jeit unape ni.',
	requirements: 'Ud aluja pipovucu.',
	risks: 'Ni kurbopriv zuwcot.',
	contribution: 'Gaoza nudta buru.',
	status: 'DRAFT',
	objectID: 'technology-1',
	users: [
		{
			id: 11,
			email: 'sabiatestinge2e@gmail.com',
			status: 'verified',
			first_name: 'FirstName',
			last_name: 'LastName',
			lattes_id: null,
			role_id: 1,
			full_name: 'FirstName LastName',
		},
	],
	terms: [
		{
			id: 2,
			term: 'Tecnologias Sociais',
			slug: 'tecnologias-sociais',
			parent_id: null,
			taxonomy_id: 3,
			taxonomy: {
				id: 3,
				taxonomy: 'CLASSIFICATION',
				description: 'Classificação da tecnologia.',
			},
			pivot: { term_id: 2, technology_id: 1 },
		},
		{
			id: 11,
			term: 'Nível 8 - Sistema real desenvolvido e aprovado',
			slug: 'nivel-8-sistema-real-desenvolvido-e-aprovado',
			parent_id: null,
			taxonomy_id: 4,
			taxonomy: {
				id: 4,
				taxonomy: 'STAGE',
				description: 'Estágio de desenvolvimento da)',
			},
			pivot: { term_id: 11, technology_id: 1 },
		},
		{
			id: 17,
			term: 'Política',
			slug: 'politica',
			parent_id: null,
			taxonomy_id: 5,
			taxonomy: {
				id: 5,
				taxonomy: 'DIMENSION',
				description: 'Dimensão da Tecnologia',
			},
			pivot: { term_id: 17, technology_id: 1 },
		},
		{
			id: 74,
			term: 'Educação',
			slug: 'educacao',
			parent_id: null,
			taxonomy_id: 1,
			taxonomy: {
				id: 1,
				taxonomy: 'CATEGORY',
				description: 'Categoria a qual pertencea',
			},
			pivot: { term_id: 74, technology_id: 1 },
		},
		{
			id: 77,
			term: 'Educação e calendário agrícola',
			slug: 'educacao-e-calendario-agricola',
			parent_id: 74,
			taxonomy_id: 1,
			taxonomy: {
				id: 1,
				taxonomy: 'CATEGORY',
				description: 'Categoria a qual pertencea',
			},
			pivot: { term_id: 77, technology_id: 1 },
		},
		{
			id: 78,
			term: 'Agricultores',
			slug: 'agricultores',
			parent_id: null,
			taxonomy_id: 6,
			taxonomy: {
				id: 6,
				taxonomy: 'TARGET_AUDIENCE',
				description: 'Público-alvo da tecnologia',
			},
			pivot: { term_id: 78, technology_id: 1 },
		},
		{
			id: 82,
			term: 'Caatinga',
			slug: 'caatinga',
			parent_id: null,
			taxonomy_id: 7,
			taxonomy: {
				id: 7,
				taxonomy: 'BIOME',
				description: 'Bioma no qual se insere a tecnologia (Caatinga, Zona da Mata, etc)',
			},
			pivot: { term_id: 82, technology_id: 1 },
		},
		{
			id: 85,
			term: 'Mais Nordeste',
			slug: 'mais-nordeste',
			parent_id: null,
			taxonomy_id: 8,
			taxonomy: {
				id: 8,
				taxonomy: 'GOVERNMENT_PROGRAM',
				description: 'Programas de governos (Bolsaa',
			},
			pivot: { term_id: 85, technology_id: 1 },
		},
		{
			id: 87,
			term: 'Propriedade Intelectual 2',
			slug: 'propriedade-intelectual-2',
			parent_id: null,
			taxonomy_id: 9,
			taxonomy: {
				id: 9,
				taxonomy: 'INTELLECTUAL_PROPERTY',
				description: 'Propriedade intelectual da tecnologia',
			},
			pivot: { term_id: 87, technology_id: 1 },
		},
	],
	reviews: [],
	bookmarkUsers: [
		{
			id: 1,
			email: 'wikcu@ubi.uz',
			status: 'pending',
			first_name: 'H9F96LNQIGJT',
			last_name: 'zV$vWh0)@',
			company: 'RbSRxYJWQuhkkj)hsTs',
			zipcode: '60130',
			cpf: '82040962035',
			birth_date: '2020-04-11 05:19:40.206',
			phone_number: '99650883715',
			lattes_id: '58947968425',
			address: '1y%7([mWNr',
			address2: '$])]mBixzaNL',
			district: '6F2hPculXh(r*',
			city: '4m@u]mxnZBZ',
			state: '15l7o',
			country: '3oToGE^g$WVyp7i)ut',
			role_id: 1,
			full_name: 'H9F96LNQIGJT zV$vWh0)@',
			pivot: { user_id: 1, technology_id: 1 },
		},
	],
	technologyCosts: {
		id: 1,
		funding_required: 1,
		funding_type: 'collective',
		funding_value: 44546307,
		funding_status: 'acquiring',
		notes: 'De sutuvga eca icecibjo.',
		technology_id: 1,
		costs: {
			maintenance_costs: [
				{
					id: 1,
					description: 'Jief osaser hepuchon.',
					type: 'equipment',
					quantity: 55,
					value: 5835540,
				},
				{
					id: 3,
					description: 'Ojohapras fitnegowu jalpenada cof.',
					type: 'service',
					quantity: 45,
					value: 3388497,
				},
			],
			implementation_costs: [
				{
					id: 2,
					description: 'Tofdezti bagavoh rutkorzum koba.',
					type: 'equipment',
					quantity: 28,
					value: 33763160,
				},
			],
		},
	},
	thumbnail: null,
	taxonomies: {
		keywords: 'Antelope, Python, Jaguarundi, Olive Sea Snake, Woodswallow',
		classification: 'Tecnologias Sociais',
		stage: 'Nível 8 - Sistema real desenvolvido e aprovado',
		dimension: 'Política',
		category: 'Educação, Educação e calendário agrícola',
		target_audience: 'Agricultores',
		biome: 'Caatinga',
		government_program: 'Mais Nordeste',
		intellectual_property: 'Propriedade Intelectual 2',
	},
};

test('it render the technology details page', () => {
	const { container } = render(
		<Page technology={technology} relatedTechnologies={[{ ...technology }]} />,
	);

	expect(container).toMatchSnapshot();
});
